services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 16189251
      POSTGRES_DB: taskmanager
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:16189251@db:5432/taskmanager
    depends_on:
      - db
volumes:
  db_data:

